export const GET_CHARACTERS_LIST = 'GET_CHARACTERS_LIST';
export const GET_CHARACTERS_LIST_LOADING = 'GET_CHARACTERS_LIST_LOADING';
export const GET_CHARACTERS_LIST_ERROR = 'GET_CHARACTERS_LIST_ERROR';

export const BLACKLIST_CHARACTER = 'BLACKLIST_CHARACTER';
export const BLACKLIST_CHARACTER_LOADING = 'BLACKLIST_CHARACTER_LOADING';
export const BLACKLIST_CHARACTER_CLEAR = 'BLACKLIST_CHARACTER_SUCCESS';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_SEARCH = 'CHANGE_SEARCH';
