export const GET_CHARACTERS_LIST = 'GET_CHARACTERS_LIST';
export const GET_CHARACTERS_LIST_LOADING = 'GET_CHARACTERS_LIST_LOADING';
export const GET_CHARACTERS_LIST_ERROR = 'GET_CHARACTERS_LIST_ERROR';

export const GET_CHARACTERS_LIST_SEARCH = 'GET_CHARACTERS_LIST_SEARCH';
export const GET_CHARACTERS_LIST_SEARCH_ERROR = 'GET_CHARACTERS_LIST_SEARCH_ERROR';

export const BLACKLIST_CHARACTER = 'BLACKLIST_CHARACTER';
export const BLACKLIST_CHARACTER_LOADING = 'BLACKLIST_CHARACTER_LOADING';
export const BLACKLIST_CHARACTER_REMOVE = 'BLACKLIST_CHARACTER_SUCCESS';
export const BLACKLIST_CHARACTER_ERROR = 'BLACKLIST_CHARACTER_ERROR';
