export const GET_CHARACTER_DETAILS_SUCCESS = 'GET_CHARACTER_DETAILS_SUCCESS';
export const GET_CHARACTER_DETAILS_ERROR = 'GET_CHARACTER_DETAILS_ERROR';
export const GET_CHARACTER_DETAILS_LOADING = 'GET_CHARACTER_DETAILS_LOADING';
export const CLEAR_CHARACTER_DETAILS = 'CLEAR_CHARACTER_DETAILS';

export const OPEN_CHARACTER_DETAILS = 'OPEN_CHARACTER_DETAILS';
export const CLOSE_CHARACTER_DETAILS = 'CLOSE_CHARACTER_DETAILS';
export const GET_SELECT_CHARACTER = 'GET_SELECT_CHARACTER';
